# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de20dac373463cac91600fe7855e6ea8aba1086300da6347d0ac03f20e3776a4d3e755648c434d99d6882393b89ad50d63c72edb09d738c10a313b5c496d6256

test:
  secret_key_base: ddf30669688d4b66f6e53d2424d37b2a34de924f8533a9580ca871a707f0167865bf315485ef1a8efcf847c98d216129c780ceb36a5e460df2dca396c4871de2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
